### ISSUE TITLE
Need to be able to read the entire metadata without downloading

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/geonode#12]
![image](https://cloud.githubusercontent.com/assets/1036189/14719005/c89a4672-07c7-11e6-811f-4e34d43c95a8.png)

The metadata should be expandable on click. It would be great to put that back into master too.

**Comment by stufraser1** [comment]
Or show whole abstract without clicking to expand

**Comment by stufraser1** [comment]
Resolved with new version of geonode 'metadata detail' button
e.g., http://www.geonode-gfdrrlab.org/layers/hazard:eq_tz_if_50/metadata_detail
