### ISSUE TITLE
Issue with the search

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/geonode#13]
Two issues: 
- [ ] the auto-suggested answer are hiding the text box so the user cannot see what he/she is typing in the text box after entering the first few characters
- [ ] the search doesn't let the user enter free text, it will replace with the automatic suggestion. For instance, try entering Ethiopia. It is not possible do a search on the word "Ethiopia"

**Comment by stufraser1** [comment]
First one recorded in #7.
Second one not replicated recently. Closing.
