### ISSUE TITLE
Cannot create new layer

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/geonode#15]
On http://54.229.171.111/layers/upload 

![capture du 2017-03-31 16-28-21](https://cloud.githubusercontent.com/assets/265319/24554781/1a2076f8-162f-11e7-8acd-8dc49b80bf9f.png)

Looks like geonode is not authorized to push data into geoserver using the rest API.

Current `security/rest.properties` config is:
```
/rest/process/batchdownload/download/*;GET=IS_AUTHENTICATED_ANONYMOUSLY         
/rest/printing/*;GET,POST=IS_AUTHENTICATED_ANONYMOUSLY                          
/**;GET=ADMIN                                                                   
/**;POST,DELETE,PUT=ADMIN
```

**Comment by fvanderbiest** [comment]
For some reason GeoNode does not use it's settings file, in which the credentials for the geoserver admin user are stored. Still investigating.

**Comment by stufraser1** [comment]
@fvanderbiest has there been any progress or resolution of this issue?

@ErikKBethke please keep an eye on this issue, to know whether you can upload new files next week

**Comment by fvanderbiest** [comment]
> has there been any progress or resolution of this issue?

I've been able to overcome this, but hit a second issue with geoserver still denying access to the REST API.

**Comment by fvanderbiest** [comment]
I think we fixed the issue, at last ! The geoserver datadir missed some migration ...
Sorry for the delay.

**Comment by stufraser1** [comment]
Excellent. 
@ErikKBethke can you please upload / replace some layers on the new geonode to confirm this works form our side.

**Comment by fvanderbiest** [comment]
We still have an issue uploading new layers: thumbnails are not generated. We're working on it.
In addition, layer + map removal is broken at the moment.

**Comment by vdeparday** [comment]
This has been a recurring issue in some installations, there should be some
resources on the mailing or in the docs to solve it.

**Comment by fvanderbiest** [comment]
> This has been a recurring issue in some installations, there should be some
> resources on the mailing or in the docs to solve it.

We think the issue is rather linked with the way the app is containerized with docker. Background tasks handled by the internal Celery app are not working. We're trying to understand how it works to fix it.

**Comment by fvanderbiest** [comment]
Not relevant anymore
