### ISSUE TITLE
Metadata detail missing items

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/geonode#18]
Add items to metadata detail page:

- [ ] hazard type
- [ ] hazard set
- [ ] return period

**Comment by fvanderbiest** [comment]
Eg on http://www.geonode-gfdrrlab.org/layers/hazard:als07_975yr/metadata_detail

**Comment by stufraser1** [comment]
@vdeparday Should we in fact not add these, given these are relevant only to TH! data?

**Comment by vdeparday** [comment]
@stufraser1 I think we can add them to GeoNode but them not display in the layer profile, or only for admin user / super user.

**Comment by vdeparday** [comment]
Confirmed that it is not necessary to have those on the public metadata page.
