### ISSUE TITLE
Transfer of styles

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/geonode#19]
Please confirm that map styles have been transferred from http://45.55.174.20/
Not many appear in http://54.229.171.111

**Comment by fvanderbiest** [comment]
Do you mean layer styles, SLDs ?

AFAIK http://www.geonode-gfdrrlab.org/geoserver/web/wicket/bookmarkable/org.geoserver.wms.web.data.StylePage?11 is up to date with latest "old production" data.

**Comment by fvanderbiest** [comment]
Not relevant anymore
