### ISSUE TITLE
Add fields to metadata template for further info on point of contact

### ISSUE THREAD

**Issue by avalenzuela00** [GFDRR/geonode#2]
Add name field that allows names other than GeoNode users
Add field for email
Add field for phone number
Add Organization field

**Comment by avalenzuela00** [comment]
![screen shot 2015-06-29 at 2 08 06 pm](https://cloud.githubusercontent.com/assets/9418919/8414872/c1b86742-1e68-11e5-8889-81c235e66d63.png)

**Comment by stufraser1** [comment]
This is given in metadata detail in new version. Closing
