### ISSUE TITLE
Metadata detail: Owner email

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/geonode#22]
Owner email displaying the wrong field? Not showing email, instead shows admin account name

**Comment by ErikKBethke** [comment]
This appears to be working correctly. See minor change to way "email" displays (now it is "Email" for consistency) in pull request #50

**Comment by ErikKBethke** [comment]
See pull request #66

**Comment by stufraser1** [comment]
Email field shows email in int server 2.8. Closing
