### ISSUE TITLE
Cannot update metadata - returns error

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/geonode#24]
Cannot update metadata, returns FailedRequestError at /layers/hazard:als07_975yr/metadata
@ErikKBethke recorded this error, has superuser account

**Comment by fvanderbiest** [comment]
Might be fixed recently, I did not witness it on http://www.geonode-gfdrrlab.org/layers/hazard:als07_975yr

**Comment by vdeparday** [comment]
May be a write permission issue on the folder where the thumbnails are
generated.

**Comment by ErikKBethke** [comment]
Error appears to be resolved, have had no issues updating metadata.
