### ISSUE TITLE
Add data categories

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/geonode#25]
We require some more meaningful data categories for the data we're uploading. Please add:
- [ ] Risk analysis - exposure data
- [ ] Risk analysis - hazard data
- [ ] Risk analysis - vulnerability data
- [ ] Risk analysis - risk output data

**Comment by stufraser1** [comment]
@ErikKBethke 
Can you look into doing this. It is not possible to add new categories at https://www.geonode-gfdrrlab.org/admin/base/topiccategory/
Nor is it possible to select multiple categories. Everything we have uploaded that is hazard data is currently geoscientific information, which is too broad a category IMO.
In this case, I suggest that data that have been specifically developed and used as part of a risk analysis are given the suggested categories above, but other data are attributed to the existing ones.

I.e.
Probabilistic seismic hazard layers would be 'risk analysis - geohazard' but seismic zone map would be 'geoscientific information'.
Probabilistic cyclone hazard layers would be 'risk analysis - hydromet hazard' but a data set of wind pressure / humidity would be 'Climatology Meteorology Atmosphere'.
Roads exposure data with values used in risk analysis would be 'Risk analysis - exposure', but an original road network data set (e.g., without values useful to risk analysis) would be 'Transportation'

thoughts, @vdeparday ?

**Comment by cgiovando** [comment]
You can add categories from https://www.geonode-gfdrrlab.org/admin/base/topiccategory/

Custom icon can be added through the `Fa class:` element in each category admin page, by selecting from http://fontawesome.io/icons/ and using the corresponding code (e.g. [`fa-github`](http://fontawesome.io/icon/github/) for the GitHub icon)

**Comment by stufraser1** [comment]
Scope of this geonode narrowed to hazard data only. Not required
