### ISSUE TITLE
Home page additions - new hazards

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/geonode#27]
Please add icons for additional hazards:
- [x] Wildfire
- [x] Extreme Heat
- [x] Urban Flood
- [x] Water scarcity
Icons from 
[newIcons-UF-WS-EH-WF-AP.zip](https://github.com/GFDRR/geonode/files/887022/newIcons-UF-WS-EH-WF-AP.zip)
to match ThinkHazard v2

**Comment by stufraser1** [comment]
@fjacon please can you action the changes to the geonode homepage (adding icons, data categories) in this and other high priority issues? We need these updates before we start marketing the geonode more heavily, which we would like to start. Thanks

**Comment by Vampouille** [comment]
@stufraser1 I'm working on adding new icons. I notice that landslide icon has wrong size: 120px instead of 64px. I can reduce 120px image size but we could have better result if we start from image source. So do you have landslide icon with big resolution ?

**Comment by Vampouille** [comment]
I also had to adjust color of new icons to match other icons color:
Original color of new icon:
![original-icon](https://user-images.githubusercontent.com/7067560/31664046-38f9f40c-b344-11e7-8b84-2c486a86917e.png)
New icon with color that match other icons color:
![hazard-icon-wildfire](https://user-images.githubusercontent.com/7067560/31664080-5d4f3be6-b344-11e7-95ed-457e433922ba.png)

**Comment by stufraser1** [comment]
Original LS icon is contained here, colour will need updating too
[DisasterIcons.zip](https://github.com/GFDRR/geonode/files/1390914/DisasterIcons.zip)

**Comment by Vampouille** [comment]
Zip archive does not contains current icon for landslide:
![hazard-icon-landslide](https://user-images.githubusercontent.com/7067560/31668684-2bf0c7c2-b353-11e7-854b-c1322dc4797d.png)

**Comment by stufraser1** [comment]
Ah yes, I supplied the icon used in TH. We should take this chance to match the geonode icons to those used for TH! and RODI sites - see below, and in the TH code. @vdeparday do you agree?

@Vampouille  this would mean updating the river FL and coastal FL icons too - icons in this PDF as well as in TH code:  [disaster_icon_june_2015_C.pdf](https://github.com/GFDRR/geonode/files/1391251/disaster_icon_june_2015_C.pdf)


CURRENT GEONODE ![image](https://user-images.githubusercontent.com/12515042/31669080-f4eb43d0-b34b-11e7-9495-ea6fb714d683.png)
CURRENT RODI SITE 
CURRENT TH ![image](https://user-images.githubusercontent.com/12515042/31669132-1eca372e-b34c-11e7-9f59-9d6d1d573f15.png)

**Comment by Vampouille** [comment]
Done with: https://github.com/Vampouille/geonode/commit/d9469cf11764d04eda6f3fd0c8aed977917c6d93 and build in docker image camptocamp/geonode_django:20171019113544 and camptocamp/geonode_django:2.7-gfdrr-ac3ab00-psycopg2.7
I just install it on int instance, run a `python manage.py collectstatic` to deploy static files and run `python manage.py migrate` to migrate database.

**Comment by Vampouille** [comment]
TODO: update river FL and coastal FL icon to match TH layout.

**Comment by Vampouille** [comment]
Also applied on prod instance

**Comment by vdeparday** [comment]
I see a layout issue on chrome with the new icons:

![image](https://user-images.githubusercontent.com/1036189/31795353-7be9b60c-b4f3-11e7-81b2-763f38f4f9c0.png)

**Comment by fjacon** [comment]
I cannot reproduce on chrome Version 62.0.3202.62.
But i am on Ubuntu.

**Comment by Vampouille** [comment]
It appears when width of browser window is less than 1200px. @tonio any idea about this layout issue ?

**Comment by tonio** [comment]
Set a height for every grid item (`.col-xs-4.col-sm-3`). Having the same height will avoid floating items to snap  on tallest elements (`15em` seems to be a good value).

**Comment by stufraser1** [comment]
To Do:
- [x] update river FL icon to match TH layout.
- [x] update coastal FL icon to match TH layout.
- [x] update landslide FL icon to match TH layout.

When these are live this issue can be closed

**Comment by Vampouille** [comment]
@stufraser1 In order to sync icons between TH and geonode, I have use same method as TH to include icons: use a dedicated font that include all icons :
https://github.com/GFDRR/thinkhazard/tree/master/thinkhazard/static/webfonts/thinkhazard/fonts
This way, we have only one file to update for all icons and this file is share between TH and geonode. I think this is the best way to keep icon synced between TH and geonode.
But I did not realize that "drought" icon is missing from font. Do you have an newer font with "drought" icon ?

**Comment by Vampouille** [comment]
About layout issue, it's fixed by : 734efa0bc43d854e778e67cbd0687b423a08b115
But not already deployed.

**Comment by stufraser1** [comment]
RE 'Do you have an newer font with "drought" icon ?'
We only use Water scarcity in TH!, so we do not have the geonode drought icon in TH. Can you include the Drought icon (the dying plant and land) into the TH file, without implementing it in the UI? In the future we may want to add that as a separate hazard, as it is distinct from water scarcity (for clarity, the tap icon) so it may be helpful to have it in there.

**Comment by Vampouille** [comment]
> Can you include the Drought icon (the dying plant and land) into the TH file, without implementing it in the UI?

yes I will try to include Drought icon in font.

**Comment by Vampouille** [comment]
I include Drought icon in font with a83aa3173d874706cf2b6dac05c3b024b63dccd7 (not deployed). I plan to deploy this update next week.

**Comment by Vampouille** [comment]
I try to include upstream modification from 2.7.x branch but this breaks login page. Issue can be found here : https://github.com/GeoNode/geonode/issues/3172
I will try to revert updates from upstream

**Comment by Vampouille** [comment]
Update int and prod instance with:
* Fix home layout: 3c8df06bbc57a9104c946bac7fddb93f29b726a2
* Fix hazard icons: f8e4c40e0847cb247bbf5be42a8f371fd4a3051a

2.7-gfdrr-ac3ab00-psycopg2.7 --> v1-20171109110306

I also introduce git tag to keep track of each rebase of gfdrr_rebase branch. Each rebase will introduce a new tag: v*X* where*X* is a counter. Currently there is one tag : v1

**Comment by Vampouille** [comment]
@stufraser1 Icons are now synced with TH! on prod and int server.

**Comment by stufraser1** [comment]
Great, looks good. Thank you. Closing
