### ISSUE TITLE
document thumbnail

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/geonode#28]
Document thumbnail should display title page of pdf documents. Currently shows some default text, no image. @vdeparday please provide the links to required item to install to enable this.

**Comment by stufraser1** [comment]
@fjacon Please could you action this as high priority.
We need to have these document thumbnails working as soon as possible for imminent publicity of the geonode

**Comment by afabiani** [comment]
Hi, on GeoNode master branch / 2.7.x branch, we already provided the possibility of creating screenshots of Documents during the upload.
The outcome is similar to this one:

![image](https://user-images.githubusercontent.com/1278021/29976567-bc342bc2-8f3a-11e7-9778-8fe58192515e.png)

The only problem is that you need to install on your system "unoconv" and libreoffice libraries, and be shure that unoconv listener 

`unoconv --listener`

is up and running. If not, GeoNode will fallback on the old document thumbnails.

https://github.com/GeoNode/geonode/blob/57fea2f47e2a51151cc46ef58370625804230a9e/geonode/documents/renderers.py#L47

**Comment by stufraser1** [comment]
@Vampouille  any progress on this one please? Would be good to have this working

**Comment by stufraser1** [comment]
@Vampouille @fjacon Please can you action this, it is important so we can promote Geonode more widely.

**Comment by vdeparday** [comment]
if I remember correctly, I think we need to log in, and do it manually from the user interface. We can do bulk (per page).

**Comment by stufraser1** [comment]
I am hoping we can have the "unoconv" and libreoffice libraries installed as advised, which will mean the thumbnails update automatically. Manual update is not a realistic option. @Vampouille are you able to install these libraries please?

**Comment by Vampouille** [comment]
It's not working within docker python:2.7 based on debian jessie and also not working on python:2.7-stretch based on debian stretch. But it works on native (non-docker) debian stretch without X server. Within docker image, it only work with image based on Ubuntu xenial. I will try to find what's wrong with python:2.7-stretch and also try with ubuntu xenial docker images.

**Comment by Vampouille** [comment]
I just update int instance with v2-20171123173713 version of geonode that include a working unoconv. Unfortunately it is based on ubuntu xenial. 
I also upload a test document:
https://int.geonode-gfdrrlab.org/documents/?limit=100&offset=0
Thumbnail is correctly generated.
This commit: https://github.com/GFDRR/geonode/commit/c9c04e117e68ab1b8650b11d53e4883bc6dce2df add needed dependencies to run unoconv.

**Comment by stufraser1** [comment]
@Vampouille  Thank you - do you know whether we can enable the thumbnails of all existing documents, or is it only new documents that will have the thumbnail enabled? 
Is this ready to implement on public version of Geonode?

**Comment by fjacon** [comment]
It will be necessary to write a script to enable thumbnails on existing documents.

**Comment by Vampouille** [comment]
> Is this ready to implement on public version of Geonode?

Modifications only impact docker image, no change in geonode code. I will contribute installation of unoconv to dockerize PR (https://github.com/GeoNode/geonode/pull/3451)

**Comment by Vampouille** [comment]
Document : WB_SWIO_RAFI_Component_4_RiskProfiles_Final_Report_uiKXkto.pdf seems to be corrupted.

**Comment by stufraser1** [comment]
Interesting - I think that was the document I updated metadata for, to see if it would refresh with a thumbnail. I'll replace the file.

**Comment by stufraser1** [comment]
@fjacon 
RE 'It will be necessary to write a script to enable thumbnails on existing documents.'
Please factor this into job planning - we'll need to have all documents thumbnail-enabled.

**Comment by fjacon** [comment]
I told @Vampouille to enable  thumbnails on existing documents and push to geonode prod. 
It looks like we can do it this week.

**Comment by Vampouille** [comment]
I start a script to update thumbnails for current documents on int instance, it will takes several hours.

**Comment by Vampouille** [comment]
Thumbnail are now generated on prod instance for local document. I cannot generate thumbnail for external documents. There is 230 new thumbnails, 2 documents cannot be converted : 
* [827](https://www.geonode-gfdrrlab.org/documents/827) - Detailed island risk assessment in Maldives - Hazard profiles and physical vulnerability Vol 1 - Synthesis Report
* [806](https://www.geonode-gfdrrlab.org/documents/806) - Developing a National Risk Profile of Lao PDR: Part 1 Hazard Assessment

**Comment by stufraser1** [comment]
@Vampouille  thank you - so when we upload new documents, they will automatically create a thumbnail?
'External docs' - these are ones with a URL to website or pdf, rather than a pdf stored on geoserver?

**Comment by Vampouille** [comment]
> so when we upload new documents, they will automatically create a thumbnail?

yes

> 'External docs' - these are ones with a URL to website or pdf, rather than a pdf stored on geoserver?

yes

**Comment by stufraser1** [comment]
Tested a document upload, thumbnail generated. Closing. Thanks @Vampouille
