### ISSUE TITLE
List of available styles

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/geonode#30]
Please show list of available styles in alphbetical order:
@ http://www.geonode-gfdrrlab.org/gs/hazard:<layername>/style/manage
e.g., http://www.geonode-gfdrrlab.org/gs/hazard:eq_ke_pgarp_100/style/manage

It is currently impossible to find existing styles by name.

**Comment by stufraser1** [comment]
see #63

**Comment by fvanderbiest** [comment]
PR proposed upstream with https://github.com/GeoNode/geonode/pull/3604

**Comment by fvanderbiest** [comment]
Cannot push this to int server, since the docker build step cannot be reproduced.
It fails at this step:
https://github.com/GFDRR/geonode/blob/8535c508b0b0fb38ce893cf5ed53478784035239/Dockerfile#L65
```
root@40464b693f00:/usr/src/app/geonode/static# bower --allow-root install
...
bower fastsearch#~1                                          resolved https://github.com/dbrekalo/fastsearch.git#1.11.1
bower jquery-tree-multiselect#*                            EMALFORMED Failed to read /tmp/06b8329dd9c62ab6b8a114b707d641a6/bower/fbcd535de17eb2ada57fc53f0e5abf31-4119-DBcqyw/bower.json

Additional error details:
Unexpected string in JSON at position 468
```

Since there was a message invitating to migrate from `bower` to `yarn`, @tonio and I gave a try at https://github.com/sheerun/bower-away but this did not succeed.

This requires a deeper look.

**Comment by Vampouille** [comment]
GeoNode#3604 has been merged in 2.7.x branch

**Comment by Vampouille** [comment]
In manage page, style are displayed in alphabetic order. But it only show internal generated name : bel_adm0_2428891c instead of title field of the style : "A test".

I created an issue upstream: https://github.com/GeoNode/geonode/issues/3824

**Comment by Vampouille** [comment]
I added the label fix-on-2.8 and created a dedicated issue for style name https://github.com/GFDRR/geonode/issues/78

**Comment by fjacon** [comment]
@stufraser1 geonode 2.8 is deployed on integration server
https://int.geonode-gfdrrlab.org/
this issue is solved. Can you check ?

**Comment by stufraser1** [comment]
Styles now listed alphabetically on int server. Closing.
