### ISSUE TITLE
New SSH key on github account

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/geonode#32]
@Vampouille 
Please could you add the new key on my account to https://github.com/orgs/camptocamp/teams/geonode-gfdrr , and restart the stack?
Please add 'Stu Geonode Connection key' for which I have a private key to use in filezilla. I dont have a private key to use, for the key generated by github for windows, which you added previously.

Thank you

**Comment by Vampouille** [comment]
I just restart SFTP access, you should be able to connect to SFTP server with following keys : 

* stufraser1_20131739
* stufraser1_23025131

**Comment by stufraser1** [comment]
able to connect now IP issue resolved
