### ISSUE TITLE
Upgrade GeoNode to 2.6

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/geonode#36]
We already discussed this, but just in case it was officially released today. See https://lists.osgeo.org/pipermail/geonode-users/2017-May/003097.html

**Comment by fvanderbiest** [comment]
http://int.geonode-gfdrrlab.org/ is now running 2.6 and we have a stable upgrade procedure from old production geonode.

**Comment by fvanderbiest** [comment]
Now http://www.geonode-gfdrrlab.org/ too
