### ISSUE TITLE
Nasa Data-Problem Downloading Proper Geotiff

### ISSUE THREAD

**Issue by avalenzuela00** [GFDRR/geonode#4]

**Comment by avalenzuela00** [comment]
Sorry, forgot to comment. For some reason when I download the nasa data, Aria Dpm, it is not coming out in a file format recognized by Qgis. Figured this is something we should look at.

**Comment by avalenzuela00** [comment]
@ingenieroariel

**Comment by stufraser1** [comment]
Not issue specific to this layer, closing and creating a more relevant issue
