### ISSUE TITLE
Cannot log out of GeoNode

### ISSUE THREAD

**Issue by ErikKBethke** [GFDRR/geonode#43]
Upon attempting logout of http://int.geonode-gfdrrlab.org/, receive a KeyError at /account/logout/.

Attaching error log.
[KeyError at _account_logout_.pdf](https://github.com/GFDRR/geonode/files/1036013/KeyError.at._account_logout_.pdf)

**Comment by fvanderbiest** [comment]
This should be fixed now.

**Comment by ErikKBethke** [comment]
Confirmed to be fixed, thanks!

Closing.
