### ISSUE TITLE
SSL issues

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/geonode#46]
https://int.geonode-gfdrrlab.org/ is now available with SSL, which is a pre-requisite to https://github.com/GFDRR/thinkhazard/issues/691

... but browser barks about mixed content (eg: gravatar)

**Comment by fvanderbiest** [comment]
but also:
 * http://a.tile.stamen.com/toner-lite/0/0/0.png 
 * thumbs, eg http://int.geonode-gfdrrlab.org/uploaded/thumbs/layer-22b54d92-3bc9-11e7-b6c4-040146164b01-thumb.png

**Comment by fvanderbiest** [comment]
Also this breaks uploads on INT.
It might be related to https://github.com/camptocamp/terraform-geonode/blob/master/rancher-environments/gfdrr-geonode-prod/stacks.tf#L120

**Comment by Vampouille** [comment]
We also need to update db in order to replace link with http scheme to https.

**Comment by Vampouille** [comment]
> Also this breaks uploads on INT.

Link to geoserver updated by https://github.com/camptocamp/terraform-geonode/commit/cb50ed00e9c4585aa3496687b3ba196047fdc1ed and deployed on int

**Comment by Vampouille** [comment]
> thumbs, eg http://int.geonode-gfdrrlab.org/uploaded/thumbs/layer-22b54d92-3bc9-11e7-b6c4-040146164b01-thumb.png

fixed in int db

**Comment by fvanderbiest** [comment]
@stufraser1 on https://int.geonode-gfdrrlab.org/ we have all ressources loaded through https now.
We'll check everything goes well when harvesting from TH, and then we'll plan an upgrade of production geonode.

**Comment by Vampouille** [comment]
> (eg: gravatar)

Fix in int `local_settings.py` with AVATAR_GRAVATAR_SSL

**Comment by Vampouille** [comment]
> http://a.tile.stamen.com/toner-lite/0/0/0.png

Should be fixed with https://github.com/camptocamp/labs_geonode/pull/1
