### ISSUE TITLE
Cache not logging new styles

### ISSUE THREAD

**Issue by avalenzuela00** [GFDRR/geonode#5]
Many layers that I have changed are showing up in the thumbnails properly. One layer in particular I updated days ago, and it still is not appearing correctly in the thumbnail.

**Comment by avalenzuela00** [comment]
@ingenieroariel

**Comment by ingenieroariel** [comment]
link?

**Comment by avalenzuela00** [comment]
http://45.55.174.20/layers/hazard%3Afluvial_undefended_1in10_tile_1

**Comment by stufraser1** [comment]
Not replicated lately. Closing
