### ISSUE TITLE
Additions to Hazard units not showing in public site

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/geonode#55]
Additions made in June to 
https://github.com/GFDRR/geonode/blob/hosting/geonode/base/enumerations.py
Are not showing in https://www.geonode-gfdrrlab.org metadata options.

Specifically units:
FWI - Canadian Fire Weather Index 
FAI - Flooded area intensity

**Comment by fvanderbiest** [comment]
Here's what happens:
 * you commit to https://github.com/GFDRR/geonode/commits/hosting
 * we build images & deploy from https://github.com/camptocamp/labs_geonode/commits/labs_geonode_2.6.x

Our fault, sorry for that.
I'll cherry pick your commit, then make your repository the default one to build from.

**Comment by fvanderbiest** [comment]
Done:
 * cherry-picked your commits to `labs_geonode_2.6.x`
 * pushed branch `labs_geonode_2.6.x` to https://github.com/GFDRR/geonode
 * built a new image `camptocamp/geonode_django:20170802161031`
 * deployed it to int and prod with https://github.com/camptocamp/terraform-geonode/commit/b6d0e8e11031318bbcb3c2c12e49f55b5ba91684

Can you (or someone with repository admin rights) head to https://github.com/GFDRR/geonode/settings/branches and update the default branch to be `labs_geonode_2.6.x` ? Many thanks.

Side note to @Vampouille and a reminder to me: we should use https://github.com/GFDRR/geonode/commits/labs_geonode_2.6.x to build images (and maybe destroy https://github.com/camptocamp/labs_geonode ?)

**Comment by vdeparday** [comment]
I just set up the default branch to labs_geonode_2.6.x

**Comment by fvanderbiest** [comment]
Thanks,
`camptocamp/labs_geonode` repo has been removed.
