### ISSUE TITLE
problem uploading (documents via UI)

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/geonode#57]
The two most recently uploaded documents (both using URL, not PDF file) gave 'Internal Server Error) screen on upload.
They are stored with incorrect link: https://geonode-gfdrrlab.org/documents/?limit=100&offset=0
which is the page that lists all documents, where they should be stored at https://www.geonode-gfdrrlab.org/documents/<documentNumber>

**Comment by fvanderbiest** [comment]
Also fixed with latest deploy (featuring httplib2 upgrade https://github.com/camptocamp/labs_geonode/pull/8)

**Comment by stufraser1** [comment]
This still seems to be a problem.
https://www.geonode-gfdrrlab.org/documents/?limit=100&offset=0
Shows document 'Videos of volcanic risk - BGS'. This was uploaded with URL and error 'Internal Server Error' was received. While the document appears in this list, and has a document number created on the admin side, the upload process does not allow editing of metadata directly, and no link to the document record is assigned in the UI (it links to https://www.geonode-gfdrrlab.org/documents/?limit=100&offset=0).
Metadata can be edited by navigating separately to the Admin>documents pages, and once the metadata is edited and saved, a link to the document appears correctly in the UI (e.g. https://www.geonode-gfdrrlab.org/documents/1335).

**Comment by stufraser1** [comment]
Today, I can upload a document (https://www.geonode-gfdrrlab.org/documents/1376) but not update its metadata effectively. - I enter an abstract or supplemental information in the metadata wizard and in the advanced metadata editing facility, and it fails to update either way.

**Comment by Vampouille** [comment]
Seems to be fixed on geonode 2.8 without GFDRR patches. I create 2 documents with following external URL : 
* https://www.nat-hazards-earth-syst-sci.net/16/1049/2016/
* https://www.nat-hazards-earth-syst-sci.net/16/1049/2016/nhess-16-1049-2016.pdf

**Comment by fjacon** [comment]
@stufraser1 geonode 2.8 is deployed on integration server
https://int.geonode-gfdrrlab.org/
this issue is solved. Can you check ?

**Comment by stufraser1** [comment]
I see a new upload process, and working through that most things are successful. However, on the final 'update' request, it fails with error concerning data quality scores. However, there was no option or field visible in the process to enter these scores - see image. 

Also, the page does not display correctly (is positioned off to the right compared to all other screens) when the error message appears.

<img width="1296" alt="image" src="https://user-images.githubusercontent.com/12515042/46681740-c8b32b00-cbe3-11e8-9ce2-a1408634b7f7.png">

**Comment by fjacon** [comment]
@stufraser1 this form is a new thing in geonode 2.8
So it does not include GFDRR specific field. We could actually modify it but alernatively I think you can use "advanced Edit" to finish editing the metadata. Would that be OK as a turnaround ?

**Comment by stufraser1** [comment]
Hi
I now see that the document uploaded in any case. The workaround to use advanced edit is OK, perhaps we can add this as an issue for later (lower priority) resolution. By the way, its funny that the new form has the 'data quality statement field' which I don't believe was standard previously - this was added for TH, wasn't it?
Otherwise, closing
