### ISSUE TITLE
Exception with CSW POST requests

### ISSUE THREAD

**Issue by cgiovando** [GFDRR/geonode#59]
This might affect GeoNode master, but posting here first, since it was discovered by [GEODAB team](http://www.geodab.net/) while testing Labs GeoNode harvesting in the [GEO Portal](http://www.geoportal.org/).

@afabiani please take a look and let us know what might be the issue. Thanks!

> \<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<csw:GetRecords xmlns:dc="http://purl.org/dc/elements/1.1/"
xmlns:dct="http://purl.org/dc/terms/" xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
xmlns:ows="http://www.opengis.net/ows" xmlns:ogc="http://www.opengis.net/ogc"
xmlns:gml="http://www.opengis.net/gml" xmlns:xlink="http://www.w3.org/1999/xlink"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" resultType="results"
outputFormat="application/xml" outputSchema="http://www.isotc211.org/2005/gmd"
startPosition="1" maxRecords="10" service="CSW" version="2.0.2"
xsi:schemaLocation="http://www.opengis.net/cat/csw/2.0.2
http://schemas.opengis.net/csw/2.0.2/CSW-publication.xsd">
<csw:Query xmlns:gmd="http://www.isotc211.org/2005/gmd"
typeNames="gmd:MD_Metadata">
<csw:ElementSetName>full</csw:ElementSetName>
</csw:Query>
</csw:GetRecords>

Getting the following error:

> \<?xml version="1.0" encoding="UTF-8" standalone="no"?> 
<ows:ExceptionReport xmlns:csw="http://www.opengis.net/cat/csw/2.0.2"
xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:dct="http://purl.org/dc/terms/"
xmlns:gmd="http://www.isotc211.org/2005/gmd"
xmlns:gml="http://www.opengis.net/gml" xmlns:ows="http://www.opengis.net/ows"
xmlns:xs="http://www.w3.org/2001/XMLSchema"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" language="en" version="1.2.0"
xsi:schemaLocation="http://www.opengis.net/ows
http://schemas.opengis.net/ows/1.0.0/owsExceptionReport.xsd">
<ows:Exception exceptionCode="NoApplicableCode" locator="service">
<ows:ExceptionText>Exception: the document is not valid.
Error: Element '{http://www.opengis.net/cat/csw/2.0.2}GetRecords', attribute 'resultType':
[facet 'enumeration'] The value '' is not an element of the set {'results', 'hits',
'validate'}.</ows:ExceptionText>
</ows:Exception>
</ows:ExceptionReport>

**Comment by afabiani** [comment]
Check the version of pycsw. I'm aware of a recent version having issues with lxml library and not working properly.

**Comment by cgiovando** [comment]
Thanks, @afabiani - can you tell us what version is confirmed to work?

@fvanderbiest can you double check what version we have on the Lab's instance?

**Comment by afabiani** [comment]
On GeoNode master branch we are currently using 2.0.3, and it's working
quite well.

**Comment by fvanderbiest** [comment]
It's supposed to be 2.0.2 as per https://github.com/GFDRR/geonode/blob/e9f6228025e6819a5392930a880ef04d73ebd67d/requirements.txt#L61

**Comment by stufraser1** [comment]
@cgiovando Is this still an issue? If so, what are next steps / identified resolution for this?

**Comment by stufraser1** [comment]
@cgiovando Is this still an issue? If so, what are next steps / identified resolution for this?

**Comment by stufraser1** [comment]
Can we close?

**Comment by cgiovando** [comment]
Lab's GeoNode layers seem to be harvested correctly by geoportal.org - so I think we can close this
