### ISSUE TITLE
Dragging files into window to download not working properly

### ISSUE THREAD

**Issue by avalenzuela00** [GFDRR/geonode#6]
@ingenieroariel

**Comment by vdeparday** [comment]
Do you mean to upload? Could you provide the version of the browser you are
using? And maybe a screenshot or description of what is not working so we
can sure to reproduce it. Thank you.

**Comment by avalenzuela00** [comment]
I'm running on the most recent version of chrome and safari, but neither are working. 
![screen shot 2015-06-26 at 4 58 35 pm](https://cloud.githubusercontent.com/assets/9418919/8387221/d267db2c-1c24-11e5-8ca6-260f25bf745a.png)

**Comment by avalenzuela00** [comment]
The screen shot is after I dragged 10 files into the 'drop files here'

**Comment by stufraser1** [comment]
Not replicated recently by several users. Closing
