### ISSUE TITLE
Options to access geonode server

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/geonode#60]
IP ranges have proven to be unreliable (have already needed to open from 1 IP address, to a range of IPs to a wider range of IPs in the case of automatically changing IPs).
Is there a suitable alternative that will facilitate access from the WB - use of particular SSH keys, for example?
@vdeparday  @ErikKBethke  pls add any specific requirements for WB access

**Comment by vdeparday** [comment]
@fvanderbiest we really need to be able to administrate from the WB network. Could we put this issue as a higher priority? Could you suggest alternative to whitelisting IP? Thank you.

**Comment by Vampouille** [comment]
> we really need to be able to administrate from the WB network.

It seems that ip range are not wide enough to always match your ip address so we will open ssh service to all ip addresses. @saimonn can you remove ip filter on gfdrr prod server ?

**Comment by saimonn** [comment]
I just opened the ports `tcp/2222` & `2223` without IP filtering. I kept the IP range filters on the `tcp/5432` port though.

**Comment by fvanderbiest** [comment]
Closing. 
Please reopen if required.
