### ISSUE TITLE
Maintenance on geonode server

### ISSUE THREAD

**Issue by Vampouille** [GFDRR/geonode#61]
Our sysadmin team need to make an update on geonode server. They need to change type of ip address allocated to the server to an "Elastic IP". Without this Elastic IP, if we shutdown the server, it may loose its IP address and catch another IP address after reboot.
This maintenance will take around 5 minutes based on dns propagation duration.

@stufraser1 When can we make this maintenance ?

**Comment by fvanderbiest** [comment]
To my knowledge, GeoNode is only used by TH. 
No worries as long no one fires `make harvest` in the mean time.

**Comment by fvanderbiest** [comment]
Done.
