### ISSUE TITLE
Unable to update styles

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/geonode#63]
The style editing feature on GeoNode is full of bugs. 
Working on https://www.geonode-gfdrrlab.org/layers/hazard:ts_mih_rp100
I have been able twice to assign a new style to a layer, and edit values and colours of the style, but this does not save when complete. Other times I'm unable to even open the style editing window, or change the style which is shown in the map window. It is very unreliable and frustrating that a style will not be retained once complete.

**Comment by stufraser1** [comment]
List various issues [Erik]

Short term: Try new SLD export from QGIS and upload in GeoServer Backend

Medium term option:
Possible to add alternative styling and mapping client? - from other GeoNode community members.
Look into options.
Switching to QGIS-Server

**Comment by Vampouille** [comment]
Tested on geonode 2.8 (without GFDRR patches)

* Creation of style works :
![capture du 2018-06-06 12-06-49](https://user-images.githubusercontent.com/7067560/41032654-55c9a0ae-6984-11e8-9390-521c18379650.png)

**Comment by Vampouille** [comment]
* Manage style page does not save modification :
![capture du 2018-06-06 12-07-30](https://user-images.githubusercontent.com/7067560/41032693-7efc9a8a-6984-11e8-80b2-6c7b93c4a034.png)
![capture du 2018-06-06 12-07-55](https://user-images.githubusercontent.com/7067560/41032727-91d7713e-6984-11e8-8821-72f787ad4913.png)
![capture du 2018-06-06 12-12-33](https://user-images.githubusercontent.com/7067560/41032737-959b0150-6984-11e8-8473-458e3a740583.png)



* Styles are correctly generate in geoserver : 
![capture du 2018-06-06 12-13-59](https://user-images.githubusercontent.com/7067560/41032749-a11c626c-6984-11e8-849b-6c9f95a2ee09.png)

If I change style from geoserver interface, style are applied on layer :

![capture du 2018-06-06 12-18-30](https://user-images.githubusercontent.com/7067560/41032823-d573be66-6984-11e8-99e5-c5b3005f65e1.png)

**Comment by Vampouille** [comment]
So on 2.8 : 
* creation of style works 
* manage style does not work

**Comment by stufraser1** [comment]
@Vampouille  I was able to manage styles (adding two existing styles to a layer) on a few layers in the interface. Returning to the layer and the style editor, the additional styles are shown so they have been saved.
Can it be closed?

**Comment by fjacon** [comment]
I think you can close as it is fixed on 2.8 on seems to be working on integration server
