### ISSUE TITLE
Load on prod host due to geoserver

### ISSUE THREAD

**Issue by Vampouille** [GFDRR/geonode#65]
There is currently a high load on prod server: 27. Geoserver use all cpu at 100%. @stufraser1 are you using geoserver (publish layers) ?

Can I reboot geoserver to fix load ?

**Comment by stufraser1** [comment]
No Im not using it, please go ahead

**Comment by Vampouille** [comment]
geoserver has filled temp directory of geoserver image so root partition was full. I delete tomcat temp dir and restart geoserver.
Everything is working now, but we have an issue on our side about monitoring: disk usage and memory used does not reflect real usage on host. I will try to fix this.
