### ISSUE TITLE
GAR17 - projection preventing layer showing

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/geonode#67]
![image](https://user-images.githubusercontent.com/1036189/32108890-0bec097c-bb01-11e7-86f5-8c13ad5b6605.png)

![image](https://user-images.githubusercontent.com/1036189/32108925-2287d666-bb01-11e7-9ac5-b8aff3b8928c.png)

**Comment by stufraser1** [comment]
@ErikKBethke  Have you had a look at this recently?

**Comment by stufraser1** [comment]
@mamadiocmcc checked and is resolved
