### ISSUE TITLE
Download as geotiff is not available

### ISSUE THREAD

**Issue by vdeparday** [GFDRR/geonode#69]
![image](https://user-images.githubusercontent.com/1036189/33738756-5acda14a-db68-11e7-84cb-f9680f83f05c.png)

This layer for example: 
https://www.geonode-gfdrrlab.org/layers/hazard:viento_mundo_tr50_int1

**Comment by fvanderbiest** [comment]
Looks like a permission issue with your account, since, once logged in with an admin profile, the data tab shows up.
![capture du 2018-02-08 11-02-19](https://user-images.githubusercontent.com/265319/35966934-9ea3e6b2-0cbf-11e8-907a-768bb7556ca6.png)

**Comment by fvanderbiest** [comment]
> Looks like a permission issue with your account

Nope, you were not connected...

**Comment by Vampouille** [comment]
Tested on a fresh geonode instance (without GFDRR patches) with https://github.com/olivierdalang/SPCgeonode composition.
Anonymous user can download GeoTIFF
![capture du 2018-06-06 11-51-24](https://user-images.githubusercontent.com/7067560/41031092-22f36e3e-6980-11e8-9a7c-644a8ee68cd5.png)
