### ISSUE TITLE
Search Tab: Pop-up list of layers obscures search box

### ISSUE THREAD

**Issue by avalenzuela00** [GFDRR/geonode#7]
@ingenieroariel

**Comment by avalenzuela00** [comment]
![screen shot 2015-06-29 at 12 04 19 pm](https://cloud.githubusercontent.com/assets/9418919/8412309/ff07d73e-1e56-11e5-98be-266960f18080.png)

**Comment by stufraser1** [comment]
This still occurs and needs resolving. Any popup box blocks the search field (whether it contains layer / document names, or 'no match'). Move position of box to below the search box

**Comment by ErikKBethke** [comment]
Changes have been made and the search bar obscuring is no longer are an issue.
