### ISSUE TITLE
Metadata not saving changes

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/geonode#71]
Having uploaded a document (eg. https://www.geonode-gfdrrlab.org/documents/1376) but not update its metadata effectively. - I enter an abstract or supplemental information in the metadata wizard and in the advanced metadata editing facility, and it fails to update either way.

**Comment by Vampouille** [comment]
I tested on a local instance and it seems to work. @stufraser1 Do you still have a problem ?

**Comment by stufraser1** [comment]
Yes, I tried to update text (with a very short string) in the abstract and supplemental information and it does not update when tested on:
 https://www.geonode-gfdrrlab.org/layers/hazard:wgs_hazard_viet500_1km 

but does when tested on
https://www.geonode-gfdrrlab.org/layers/hazard:wgs_fsm50_1km#more

**Comment by Vampouille** [comment]
This layer : https://www.geonode-gfdrrlab.org/layers/hazard:wgs_hazard_viet500_1km/metadata_advanced have no category selected so it cannot be updated. You need to select a category at the bottom of the edit page.

**Comment by stufraser1** [comment]
This seems to be resolved on int server with 2.8
