### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by fvanderbiest** [GFDRR/geonode#76]
Issue description at https://github.com/GFDRR/geonode/issues/30#issuecomment-364095720

**Comment by Vampouille** [comment]
I rebase V2 branch against 2.6.x : https://github.com/GFDRR/geonode/tree/test_rebase_2.6.x
Now we have all commits dedicated to gfdrr on top of 2.6.x branch.

I have successfully build a docker image with : https://github.com/olivierdalang/SPCgeonode
I just have to change :
https://github.com/olivierdalang/SPCgeonode/blob/master/requirements.txt#L3
to `https://github.com/GFDRR/geonode/archive/test_rebase_2.6.x.zip`

**Comment by Vampouille** [comment]
master branch of https://github.com/olivierdalang/SPCgeonode composition use 2.7.x branch of geonode (geonode 2.8)
So with the help of previous composition we can build a standard genode image for 2.8

We need to test with GFDRR patches

**Comment by fjacon** [comment]
Geonode 2.8 + GFDRR Patches successfully deploy on integration server. I close
