### ISSUE TITLE
Layer legend not showing 

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/geonode#81]
@pvalsecc @fjacon 
An urgent issue to resolve please:
Layer legends seem broken on v2.8 - no data showing in the map window and legend has a broken icon / no legend.

**Comment by fjacon** [comment]
OK, we will look at this

**Comment by pvalsecc** [comment]
@stufraser1, it should be fixed, now. Please check.

**Comment by stufraser1** [comment]
Confirmed as fixed. Thank you
