### ISSUE TITLE
some thumbnails broken

### ISSUE THREAD

**Issue by stufraser1** [GFDRR/geonode#82]
In some layers, the thumbnail does not load, but when on the layer page, the map does show, suggesting it is not an issue with the legend.
e.g https://www.geonode-gfdrrlab.org/search/?title__icontains=CY-GLO&limit=20&offset=0

<img width="630" alt="image" src="https://user-images.githubusercontent.com/12515042/48827546-6eba8f00-ed65-11e8-89d1-f0e8013bb3dc.png">

**Comment by pvalsecc** [comment]
For reference, query to fix that in the DB:
```
UPDATE base_resourcebase
SET thumbnail_url=replace(thumbnail_url, 'https://www.geonode-gfdrrlab.org/media/thumbs/',
    'https://www.geonode-gfdrrlab.org/uploaded/thumbs/')
WHERE thumbnail_url LIKE 'https://www.geonode-gfdrrlab.org/media/thumbs/%';
```
